# Generated by Django 4.1.7 on 2023-04-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keys",
            name="block",
            field=models.BooleanField(default=True, verbose_name="Блокировка"),
        ),
        migrations.AlterField(
            model_name="keys",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания действия"),
        ),
        migrations.AlterField(
            model_name="keys",
            name="id_org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AlterField(
            model_name="keys",
            name="key",
            field=models.UUIDField(verbose_name="Ключ"),
        ),
        migrations.AlterField(
            model_name="keys",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала действия"),
        ),
    ]
